#Requires AutoHotkey v2-b+
#Include "Common.ahk"

FileEncoding "UTF-8-RAW"
SetWorkingDir A_ScriptDir "\..\source"

g_namedKeys := Set(
	; --- Mouse ---

	; General buttons
	'LButton', 'RButton', 'MButton',
	; Advanced buttons
	'XButton1', 'XButton2',
	; Wheel
	'WheelDown', 'WheelUp', 'WheelLeft', 'WheelRight',

	; --- Keyboard ---

	; General keys
	'CapsLock', 'Space', 'Tab', 'Enter', 'Escape', 'Esc', 'Backspace', 'BS',
	; Cursor control keys
	'ScrollLock', 'Delete', 'Del', 'Insert', 'Ins', 'Home', 'End', 'PgUp', 'PgDn',
	'Up', 'Down', 'Left', 'Right',
	; Named numpad keys
	'NumpadIns', 'NumpadEnd', 'NumpadDown', 'NumpadPgDn', 'NumpadLeft', 'NumpadClear',
	'NumpadRight', 'NumpadHome', 'NumpadUp', 'NumpadPgUp', 'NumpadDot', 'NumpadDel',
	'NumLock', 'NumpadDiv', 'NumpadMult', 'NumpadAdd', 'NumpadSub', 'NumpadEnter',
	; Modifier keys
	'LWin', 'RWin', 'Control', 'Ctrl', 'Alt', 'Shift', 'LControl', 'LCtrl', 'RControl',
	'RCtrl', 'LShift', 'RShift', 'LAlt', 'RAlt',
	; Multimedia keys
	'Browser_Back', 'Browser_Forward', 'Browser_Refresh', 'Browser_Stop', 'Browser_Search',
	'Browser_Favorites', 'Browser_Home', 'Volume_Mute', 'Volume_Down', 'Volume_Up',
	'Media_Next', 'Media_Prev', 'Media_Stop', 'Media_Play_Pause', 'Launch_Mail',
	'Launch_Media', 'Launch_App1', 'Launch_App2',
	; Other keys
	'AppsKey', 'PrintScreen', 'CtrlBreak', 'Pause', 'Help', 'Sleep',

	; --- Others ---

	; Special AltTab actions (these aren't actually keys, but they are used as "remap" targets)
	'AltTab', 'ShiftAltTab', 'AltTabMenu', 'AltTabAndMenu', 'AltTabMenuDismiss',
)

; Add numbered numpad keys
Loop 10
	g_namedKeys.Add('Numpad' (A_Index-1))

; Add function keys
Loop 24
	g_namedKeys.Add('F' A_Index)

props := "# This file is autogenerated by " A_ScriptName " - DO NOT UPDATE MANUALLY`n`n"
props .= "ahk.keywords.named.keys=\`n"
props .= CreateKeywordList(g_namedKeys)

FileRewrite "ahk.keys.properties", props

api := CreateApiList(g_namedKeys)

FileRewrite "ahk.keys.api", api
